- docker-compose.yaml
- sof_wrapper.env.default
- sof_wrapper/api/views.py
- sof_wrapper/auth/views.py
- sof_wrapper/config.py
* Expose SoF credentials and context for front-end to consume
Todo:
* Add CORS whitelist
* Dynamic r4 parameters
> Frontend Authentication

- sof_wrapper.env.default
- sof_wrapper/api/__init__.py
- sof_wrapper/api/fhir.py
- sof_wrapper/app.py
- sof_wrapper/config.py
* Pass PDMP API through SoF wrapper
Todo:
* Pass querystring params
* OAuth client credential flow
> PDMP Passthrough

- sof_wrapper/auth/views.py
* Remove hard-coded ISS param
* Pass given ISS back to EHR as `aud` param
* Persist between requests through session var
* Cleanup logging
> Dynamically set ISS

- sof_wrapper.env.default
- sof_wrapper/api/fhir.py
- sof_wrapper/config.py
* Add API endpoint to pass through Observation queries
> ODH Query API

- sof_wrapper/api/views.py
- sof_wrapper/auth/helpers.py
- sof_wrapper/auth/views.py
- tests/test_auth.py
No longer relying on session - extract available parameters when found.
> Round 2 for logging launch and login

- sof_wrapper/auth/views.py
- sof_wrapper/config.py
These are typically detected from the FHIR conformance statement
> Add config fallback for SoF auth endpoints

- docker-compose.yaml
- requirements.dev.txt
- requirements.txt
- setup.cfg
- sof_wrapper/app.py
- sof_wrapper/config.py
- sof_wrapper/extensions.py
Server side sessions via REDIS
> server side session 

- .github/workflows/test-build-deliver.yaml
- .gitignore
- requirements.dev.txt
- setup.cfg
- sof_wrapper/api/fhir.py
- sof_wrapper/app.py
- sof_wrapper/auth/views.py
- sof_wrapper/config.py
- tests/conftest.py
- tests/test_fhir.py
- tests/test_fhir/MedicationRequestBundleR4.json
- tests/test_fhir/PDMP-MedicationRequestBundleR4.json
- tests/test_fhir/PatientBJackson.json
- tox.ini
Now supports both r2 (MedicationOrder) and r4 (MedicationRequest).
Does return collated results for Brenda Jackson (due to a temporary trick to sub in a known patient on the PDMP, Darth Vader)
> Med Collate API

- sof_wrapper/auth/views.py
- tests/test_fhir.py
* Lookup SoF auth URLs by extension URL
* Add tests
> Fixup SoF Dynamic Auth Config

- sof_wrapper/api/fhir.py
- tests/test_fhir.py
* Add dosageInstruction data based on days supply and quantity dispensed
> Annotate Meds with Dosage Instructions

- sof_wrapper/api/fhir.py
* Add patient ID fallback for fEMR (when patient ID is not baked into access token)
* Add fallback for empty Bundles from EHR
> fEMR Bugfixes

- sof_wrapper/api/fhir.py
- tests/test_fhir.py
Update doseQuantity to account for repeated doses in the same time period
> Update doseQuantity for repeated doses

- sof_wrapper/api/fhir.py
* Passthrough `Accept` header
* Passback upstream response from FHIR proxy API
> Connectathon Fixes

- sof_wrapper/api/fhir.py
Reverts uwcirg/sof-api-wrapper#25
> Revert "Connectathon Fixes"

- .github/workflows/build-deliver.yaml
- .github/workflows/test.yaml
- Split test and build files
- Remove semantic versioning config
- Create docker image tags to match git tags (previously assumed working)
> Cleanup CI/CD

- sof_wrapper/api/fhir.py
- tests/test_fhir.py
Do not add `dosageInstruction` if missing in MedicationRequest FHIR
> Do not automatically add dosageInstructions

- sof_wrapper/api/fhir.py
- Include auth headers in requests to upstream FHIR server
> Passthrough Auth Headers

- sof_wrapper.env.default
- sof_wrapper/api/views.py
- sof_wrapper/app.py
- sof_wrapper/config.py
- sof_wrapper/logserverhandler.py
- sof_wrapper/rxnav.py
Configure a special logging handler (LogServerHandler) to pass INFO and above log messages in JSON format to the configured LogServer.
Fix bugs in /auditlog API; include extra parameters if POSTed
> Add LogServer to COSRI

- sof_wrapper/app.py
- sof_wrapper/config.py
- Read log level from environment variable
> Make log level configurable

- sof_wrapper/audit.py
Echo ERROR level audits to current_app.logger.error() for alert mechanism to pick up
example output:
``` {"asctime": "2021-09-21 17:49:46,450", "name": "sof_wrapper", "levelname": "ERROR", "message": "Medication, METHADONE HCL 5 MG TABLET, did not have an MME value returned, total MME and the MME overview graph are not reflective of total MME for this patient.", "patient": "REDACTED - see audit logs", "tags": ["cosri-frontend"]}```
> Echo ERROR level audits to system logs

- Dockerfile
- docker-compose.yaml
- requirements.txt
- setup.cfg
- Use gunicorn as default WSGI server
> Prod WSGI Server

- sof_wrapper/api/fhir.py
Add (debug) logging for request duration to upstream FHIR server
> Add upstream FHIR logging

- Dockerfile
Launch workers based on number of CPUs: 2n+1
> Increase number of HTTP workers

- Dockerfile
Use multiple threads instead of workers to share memory and fix session issues
See [PT#188528178](https://www.pivotaltracker.com/story/show/188528178)
> Session issues workaround

- sof_wrapper/api/fhir.py
Allow frontend to POST/PUT Communication/Request resources
> Passthrough PUT/POST from frontend

- sof_wrapper/api/fhir.py
Correctly pass HTTP method, body upstream
> CORS Fixes
